# Copyright 2022-2023 Hewlett Packard Enterprise Development LP
name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read   # permission to read other github actions
  contents: write # contents needed for compliance
  id-token: write # id-token needed for hpe-hcss/github-oidc-app which authenticates the runner to AWS ECR
  packages: read  # packages needed to read the build container
  pull-requests: write  # needed for compliance

concurrency:
  # Only allows one build per workflow & branch/PR/tag
  # cancels in-progress builds for that branch/PR/tag if a new one is submitted.
  # https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    # inputs are documented in the path below at the reusable workflow repo
    uses: hpe-cds/reusable-workflows/.github/workflows/ci-go.yml@main
